### ISSUE TITLE
Unable to run either of the prebuilt binaries on RHLE or Win VM

### ISSUE THREAD

**Issue by fluxmap** [AdvancedPhotonSource/XRF-Maps#57]
I am one of the scientists building the new medium energy spectroscopy (MEX) beamline at the Australian Synchrotron. In our internal discussions around the sorts of analysis we’d like to implement on data collected using the microprobe I came across XRF-Mapper.

XRF-Mapper looks really interesting. I’d love to play around and explore what XRF-Mapper can do but I have been unable to get the RHLE to run.

Unfortunately, I am swimming out of depth and I cannot seem get libzmq to play nicely. Are you able to offer any assistance?

Thanks.

**Comment by aglowacki** [comment]
Hi,
Which Linux distro do you use? There is a build for RHLE because that is the one used at Argonne APS, but most of the users are currently using the Windows build. I usually build it on Linux from source. If you have sudo access to install libraries I can tell you which ones you need to compile the software from source. If you don't then you can still compile it but it is a bit more of a pain because you have to compile netcdf, hdf5, and zeromq is optional for streaming. 

The software currently supports XRF scans from the APS sectors 2-ID-D, 2-ID-E, 8-BM, 9-ID-C, GSE Cars, Sec 20, and EDM (electron fluorescence microscopy ). If you are willing to share some datasets and describe them I can add an importer for your data.

If you would like to talk more you can continue this issue or email me at aglowacki [[at]] anl.gov

**Comment by aglowacki** [comment]
Prebuild binaries for windows are available to download in releases. For Linux there are compile instructions.
